title: Docs
author: opsZero, LLC
copyright: "2021-2022"
logo: logo.png
execute:
  execute_notebooks: force
latex:
  latex_documents:
    targetname: book.tex
repository:
  url: https://github.com/opszero/docs
  branch: main
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  extra_navbar: Go to <a href="https://www.opsZero.com">opsZero</a>
